apiVersion: v1
kind: Service
metadata:
  name: mysqldb
  namespace: atividade-aula-04
spec:
  ports:
  - name: "3306"
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysqldb-stfs